<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\Batch.BusinessLogic\\Batch.BusinessLogic.csproj" />
    <ProjectReference Include="..\\Ui.Shared\\Ui.Shared.csproj" />
  </ItemGroup>
</Project>
